$axure.loadCurrentPage({
  "url":"说明方式.html",
  "generationDate":new Date(1477632879083.65),
  "isCanvasEnabled":false,
  "variables":["hengping",
"zhibiao"],
  "page":{
    "packageId":"e557b951af014bed915fae05341fe25e",
    "type":"Axure:Page",
    "name":"说明方式",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"49fbb870d0b24cfd9fa58a4ffdcfd130",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"e253d1c34dca420d90ed3f155a0ff6e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/说明方式/u0.png"}},
{
          "id":"5dc5d3539d314a8b9af3150feb1552d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":310,
              "y":196},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"a1daf1ea7f9247d79adc5cf7ed9e3081",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":310,
                  "y":196},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/说明方式/u2.png"}},
{
          "id":"04b5cbb4079746c88732fdc2e1f5bc2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":520,
              "y":236},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"b27588e66adf4cfca1c89eada25bb2d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":520,
                  "y":236},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/说明方式/u2.png"}},
{
          "id":"329b70538178444e90507e6755381ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":554,
              "y":236},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"dd8df5c6c03f4802a0e9100df1ff3329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":554,
                  "y":236},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"067e21306367499ebb822b285262b104",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":310,
              "y":270},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"c5e9c1ff32834c18ae78a9d53c5f3468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":310,
                  "y":270},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/说明方式/u2.png"}},
{
          "id":"e2e2200a5fbf4bed810d493180c0c1b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"700",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":520,
              "y":310},
            "size":{
              "width":24,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"502e17489a9248b68c9d169bc09af3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold Oblique', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"700",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":520,
                  "y":310},
                "size":{
                  "width":24,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/说明方式/u2.png"}},
{
          "id":"ae1711557b2b45d48bccb0115665f0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":554,
              "y":310},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"aed1850884b24c029d8b356ffdc5014f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":554,
                  "y":310},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"840da52e6f884f1f8ed157660182851f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":552,
              "y":0},
            "size":{
              "width":129,
              "height":41}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"42d7663d7cf644f18a2d9b13cdc9bd53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":552,
                  "y":0},
                "size":{
                  "width":129,
                  "height":41}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "49fbb870d0b24cfd9fa58a4ffdcfd130":{
      "scriptId":"u0"},
    "e253d1c34dca420d90ed3f155a0ff6e7":{
      "scriptId":"u1"},
    "5dc5d3539d314a8b9af3150feb1552d7":{
      "scriptId":"u2"},
    "a1daf1ea7f9247d79adc5cf7ed9e3081":{
      "scriptId":"u3"},
    "04b5cbb4079746c88732fdc2e1f5bc2d":{
      "scriptId":"u4"},
    "b27588e66adf4cfca1c89eada25bb2d2":{
      "scriptId":"u5"},
    "329b70538178444e90507e6755381ec6":{
      "scriptId":"u6"},
    "dd8df5c6c03f4802a0e9100df1ff3329":{
      "scriptId":"u7"},
    "067e21306367499ebb822b285262b104":{
      "scriptId":"u8"},
    "c5e9c1ff32834c18ae78a9d53c5f3468":{
      "scriptId":"u9"},
    "e2e2200a5fbf4bed810d493180c0c1b3":{
      "scriptId":"u10"},
    "502e17489a9248b68c9d169bc09af3d5":{
      "scriptId":"u11"},
    "ae1711557b2b45d48bccb0115665f0db":{
      "scriptId":"u12"},
    "aed1850884b24c029d8b356ffdc5014f":{
      "scriptId":"u13"},
    "840da52e6f884f1f8ed157660182851f":{
      "scriptId":"u14"},
    "42d7663d7cf644f18a2d9b13cdc9bd53":{
      "scriptId":"u15"}}});