$axure.loadCurrentPage({
  "url":"横竖屏.html",
  "generationDate":new Date(1477632899397.81),
  "isCanvasEnabled":false,
  "variables":["hengping",
"zhibiao"],
  "page":{
    "packageId":"93feeff5558648fc9d37cfec2d5b74ce",
    "type":"Axure:Page",
    "name":"横竖屏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"54a5f46d0d0140f3a73dbca1ab3132c9",
          "label":"横竖屏",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":800,
              "height":800}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1<br> (If value of hengping equals &quot;1&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetGlobalVariableValue",
                      "arguments":[{
                          "exprType":"globalVariableLiteral",
                          "variableName":"hengping"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 横竖屏 to 横屏 fade out 500ms fade in 500ms",
                      "panelsToStates":[{
                          "panelPath":["54a5f46d0d0140f3a73dbca1ab3132c9"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]},
{
                      "action":"setPanelState",
                      "description":"Set This to 竖屏 fade out 500ms fade in 500ms",
                      "panelsToStates":[{
                          "panelPath":["54a5f46d0d0140f3a73dbca1ab3132c9"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c6a817f0110e48d5b71c784326da26b9",
              "label":"竖屏",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d3fa3931a8db44998f4c264c77760af6",
                  "label":"",
                  "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":380,
                      "height":800},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"a48c5c503c6c49da9a1641e155ee6326",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":380,
                          "height":800},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/流程图/u0.png"}},
{
                  "id":"243ba296094e4ab6891121088e69d9f4",
                  "label":"竖",
                  "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                  "panelIndex":0,
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":32,
                      "y":113},
                    "size":{
                      "width":320,
                      "height":575}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "target":{
                    "targetType":"page",
                    "url":"启动页.html",
                    "includeVariables":true}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
                "a":{
}}},
{
              "id":"a73da6ef18404b6abdbe776f541d4007",
              "label":"横屏",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7c4d53d96d9a43aaae9714c2108c1014",
                  "label":"",
                  "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":800,
                      "height":380},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"6fceb4759c094177a5f9cce263326ccc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":800,
                          "height":380},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/趋势/u17.png"}},
{
                  "id":"fb27dab467b642ae9116d9a41b77f5e3",
                  "label":"横",
                  "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                  "panelIndex":1,
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":114,
                      "y":27},
                    "size":{
                      "width":575,
                      "height":320}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "target":{
                    "targetType":"page",
                    "url":"趋势.html",
                    "includeVariables":true}},
{
                  "id":"ee7f6c80d19745818d732d7c035fb410",
                  "label":"今天-横屏",
                  "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                  "panelIndex":1,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":114,
                      "y":27},
                    "size":{
                      "width":575,
                      "height":320}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "interactionMap":{
                    "onLoad":{
                      "description":"OnLoad",
                      "cases":[{
                          "description":"Case 1<br> (If value of zhibiao equals &quot;shiyebu&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"zhibiao"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"shiyebu",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring 今天-横屏 to Front ",
                              "panelPaths":[{
                                  "panelPath":["ee7f6c80d19745818d732d7c035fb410"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"setPanelState",
                              "description":"Set 今天-横屏 to 事业部横屏",
                              "panelsToStates":[{
                                  "panelPath":["ee7f6c80d19745818d732d7c035fb410"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"Case 3<br> (Else If value of zhibiao equals &quot;zhuanchang&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"zhibiao"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"zhuanchang",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring 今天-横屏 to Front ",
                              "panelPaths":[{
                                  "panelPath":["ee7f6c80d19745818d732d7c035fb410"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"setPanelState",
                              "description":"Set 今天-横屏 to 专场横屏",
                              "panelsToStates":[{
                                  "panelPath":["ee7f6c80d19745818d732d7c035fb410"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"Case 2<br> (Else If True)",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Send 今天-横屏 to Back",
                              "panelPaths":[{
                                  "panelPath":["ee7f6c80d19745818d732d7c035fb410"],
                                  "setOrderInfo":{
                                    "bringToFront":false}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"e98eb8e623ed4574b210a2101266ced2",
                      "label":"透明",
                      "type":"Axure:PanelDiagram",
                      "objects":[],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
                        "a":{
}}},
{
                      "id":"74dc771bf36244ba830d773ade30a1ad",
                      "label":"事业部横屏",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"654ad7240eaa485e926bb71fbb799403",
                          "label":"",
                          "parentDynamicPanel":"ee7f6c80d19745818d732d7c035fb410",
                          "panelIndex":1,
                          "type":"inlineFrame",
                          "styleType":"inlineFrame",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":575,
                              "height":320}},
                          "adaptiveStyles":{
                            "a":{
}},
                          "target":{
                            "targetType":"page",
                            "url":"今日累积指标.html",
                            "includeVariables":true}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
                        "a":{
}}},
{
                      "id":"c9244d9f22b0405fb6ea12ea4f4983cf",
                      "label":"专场横屏",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"6be7a9d7934a45e8a2343cb6a55acc48",
                          "label":"",
                          "parentDynamicPanel":"ee7f6c80d19745818d732d7c035fb410",
                          "panelIndex":2,
                          "type":"inlineFrame",
                          "styleType":"inlineFrame",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":575,
                              "height":320}},
                          "adaptiveStyles":{
                            "a":{
}},
                          "target":{
                            "targetType":"page",
                            "url":"专场详情.html",
                            "includeVariables":true}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
                        "a":{
}}}]},
{
                  "id":"2cc51f2473814afdba03501b02905cae",
                  "label":"历史-横屏",
                  "parentDynamicPanel":"54a5f46d0d0140f3a73dbca1ab3132c9",
                  "panelIndex":1,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":114,
                      "y":28},
                    "size":{
                      "width":575,
                      "height":320}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "interactionMap":{
                    "onLoad":{
                      "description":"OnLoad",
                      "cases":[{
                          "description":"Case 1<br> (If value of zhibiao equals &quot;shiyebu-H&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"zhibiao"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"shiyebu-H",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring 历史-横屏 to Front ",
                              "panelPaths":[{
                                  "panelPath":["2cc51f2473814afdba03501b02905cae"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"setPanelState",
                              "description":"Set 历史-横屏 to 事业部横屏",
                              "panelsToStates":[{
                                  "panelPath":["2cc51f2473814afdba03501b02905cae"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"Case 3<br> (Else If value of zhibiao equals &quot;zhuanchang-H&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"zhibiao"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"zhuanchang-H",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring 历史-横屏 to Front ",
                              "panelPaths":[{
                                  "panelPath":["2cc51f2473814afdba03501b02905cae"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"setPanelState",
                              "description":"Set 历史-横屏 to 专场横屏",
                              "panelsToStates":[{
                                  "panelPath":["2cc51f2473814afdba03501b02905cae"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"Case 2<br> (Else If value of hengping equals &quot;KPI-H&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"hengping"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"KPI-H",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring 历史-横屏 to Front ",
                              "panelPaths":[{
                                  "panelPath":["2cc51f2473814afdba03501b02905cae"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"setPanelState",
                              "description":"Set 历史-横屏 to KPI横屏",
                              "panelsToStates":[{
                                  "panelPath":["2cc51f2473814afdba03501b02905cae"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"b8c0d70d796a4f9e90ea8a575ea6728e",
                      "label":"透明",
                      "type":"Axure:PanelDiagram",
                      "objects":[],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
                        "a":{
}}},
{
                      "id":"8239620e43aa4413be29821a86f2e650",
                      "label":"事业部横屏",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"3f36907d462f4615ab95a36e8429fe5c",
                          "label":"",
                          "parentDynamicPanel":"2cc51f2473814afdba03501b02905cae",
                          "panelIndex":1,
                          "type":"inlineFrame",
                          "styleType":"inlineFrame",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":575,
                              "height":320}},
                          "adaptiveStyles":{
                            "a":{
}},
                          "target":{
                            "targetType":"page",
                            "url":"历史-事业部运营.html",
                            "includeVariables":true}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
                        "a":{
}}},
{
                      "id":"498976d0740546c1b027bec39dc83346",
                      "label":"专场横屏",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"3590e47166fd48f5a9266344e9a9b3d8",
                          "label":"",
                          "parentDynamicPanel":"2cc51f2473814afdba03501b02905cae",
                          "panelIndex":2,
                          "type":"inlineFrame",
                          "styleType":"inlineFrame",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":575,
                              "height":320}},
                          "adaptiveStyles":{
                            "a":{
}},
                          "target":{
                            "targetType":"page",
                            "url":"历史专场明细.html",
                            "includeVariables":true}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
                        "a":{
}}},
{
                      "id":"1daafafd0ea54c4cb9cc05c0df8b6033",
                      "label":"KPI横屏",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ef4a6be94fef4e2782175bea222d8f57",
                          "label":"",
                          "parentDynamicPanel":"2cc51f2473814afdba03501b02905cae",
                          "panelIndex":3,
                          "type":"inlineFrame",
                          "styleType":"inlineFrame",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":575,
                              "height":320}},
                          "adaptiveStyles":{
                            "a":{
}},
                          "target":{
                            "targetType":"page",
                            "url":"趋势-历史.html",
                            "includeVariables":true}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
                        "a":{
}}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
                "a":{
}}}]}]}},
  "masters":{
},
  "objectPaths":{
    "54a5f46d0d0140f3a73dbca1ab3132c9":{
      "scriptId":"u0"},
    "d3fa3931a8db44998f4c264c77760af6":{
      "scriptId":"u1"},
    "a48c5c503c6c49da9a1641e155ee6326":{
      "scriptId":"u2"},
    "243ba296094e4ab6891121088e69d9f4":{
      "scriptId":"u3"},
    "7c4d53d96d9a43aaae9714c2108c1014":{
      "scriptId":"u4"},
    "6fceb4759c094177a5f9cce263326ccc":{
      "scriptId":"u5"},
    "fb27dab467b642ae9116d9a41b77f5e3":{
      "scriptId":"u6"},
    "ee7f6c80d19745818d732d7c035fb410":{
      "scriptId":"u7"},
    "654ad7240eaa485e926bb71fbb799403":{
      "scriptId":"u8"},
    "6be7a9d7934a45e8a2343cb6a55acc48":{
      "scriptId":"u9"},
    "2cc51f2473814afdba03501b02905cae":{
      "scriptId":"u10"},
    "3f36907d462f4615ab95a36e8429fe5c":{
      "scriptId":"u11"},
    "3590e47166fd48f5a9266344e9a9b3d8":{
      "scriptId":"u12"},
    "ef4a6be94fef4e2782175bea222d8f57":{
      "scriptId":"u13"}}});